project:
  type: website
  output-dir: _site

website:
  title: "site_portfolio"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: flatly
    toc: true
    code-fold: true


